[tool.poetry]
name = "dataclouder-template-python"
version = "0.0.1"
description = "python template for new projects"
authors = ["adamo jordan <adamo.figueroa@gmail.com>"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = "^3.11"
fastapi = { extras = ["all"], version = "0.110.1" }
uvicorn = { extras = ["standard"], version = "^0.29.0" }
oauth2client = "^4.1.3"
google-cloud-texttospeech = "^2.24.0"
google-generativeai = "^0.8.4"
python-dotenv = "^1.0.1"
fal-client = "^0.5.7"
pillow = "^11.1.0"
pydantic-ai = "^0.0.20"
dataclouder-conversation-ai-cards = "^0.0.7"
dataclouder-tts = "^0.0.6"
pymongo = "^4.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
